### ISSUE TITLE
Error: Provider not set or invalid     at Object.InvalidProvider (/home/ben/price-bot/node_modules/web3-core-helpers/src/errors.js:38:16)     at RequestManager.send (/home/ben/price-bot/node_modules/web3-core-requestmanager/src/index.js:128:32)     at sendRequest (/home/ben/price-bot/node_modules/web3-core-method/src/index.js:560:42)     at send (/home/ben/price-bot/node_modules/web3-core-method/src/index.js:581:13)     at Object._executeMethod (/home/ben/price-bot/node_modules/web3-eth-contract/src/index.js:826:24)     at checkPair (/home/ben/price-bot/index.js:36:96)     at monitorPrice (/home/ben/price-bot/index.js:68:11)     at Timeout._onTimeout (/home/ben/price-bot/index.js:112:48)     at listOnTimeout (internal/timers.js:554:17)     at processTimers (internal/timers.js:497:7)

### ISSUE THREAD

**Issue by MRC100** [dappuniversity/price-bot#18]
Error: Provider not set or invalid
    at Object.InvalidProvider (/home/ben/price-bot/node_modules/web3-core-helpers/src/errors.js:38:16)
    at RequestManager.send (/home/ben/price-bot/node_modules/web3-core-requestmanager/src/index.js:128:32)
    at sendRequest (/home/ben/price-bot/node_modules/web3-core-method/src/index.js:560:42)
    at send (/home/ben/price-bot/node_modules/web3-core-method/src/index.js:581:13)
    at Object._executeMethod (/home/ben/price-bot/node_modules/web3-eth-contract/src/index.js:826:24)
    at checkPair (/home/ben/price-bot/index.js:36:96)
    at monitorPrice (/home/ben/price-bot/index.js:68:11)
    at Timeout._onTimeout (/home/ben/price-bot/index.js:112:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by MRC100** [comment]
This error message happens when I enter:
npm run start

**Comment by jordanmcdougall** [comment]
I think this is similar to #14 - do you have a valid RPC URL in your .env file, also did you rename `.env.example` to just `.env`?
