### ISSUE TITLE
Error: Invalid JSON RPC response: "invalid project id\n"

### ISSUE THREAD

**Issue by samtheloanman** [dappuniversity/price-bot#24]
Hi there : ) can you please help me with this issue, I am really excited to run this bot with my daughter (9 yrs old), I am doing project based learning with her and this is one of our projects but we ran into this error when running this bot.  Please help ; )

Listening on 5000
Checking prices...
Error: Invalid JSON RPC response: "invalid project id\n"
    at Object.InvalidResponse (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-providers-http/src/index.js:92:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

This is our .env file details:

RPC_URL="https://mainnet.infura.io/v3/njpp********************"
PRIVATE_KEY="**********************************************************"
ACCOUNT="0xCf9F30Ab738FD10D9189755b83f942e7Ad83f0D6"

**Comment by samtheloanman** [comment]
Also wondering if we can run this on the testnet, we had the same error when trying the testnet

**Comment by samtheloanman** [comment]
Also just tried RPC_URL=https://mainnet.infura.io/v3/njpp********************

Removing the quotation marks, still same issue

**Comment by Abhishek-Verma8954** [comment]
same with me

**Comment by gbfandon** [comment]
how did you fix it

**Comment by 0xAskar** [comment]
Any updates?

**Comment by FedeOn360hz** [comment]
update ?

**Comment by CibolinCode** [comment]
I've gotten a lot closer using web scalping techniques with python can
easily pull up a coin and its price still trying to figure out how to
integrate it into the node.js version or whatever this other script is the
python code doesn't quite convert

**Comment by suresh-ben** [comment]
Updates??
