### ISSUE TITLE
Error: Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by samtheloanman** [dappuniversity/price-bot#25]
Hello, I am having the following issue, not sure how to fix this issue.  Please help.

> trading-bot@0.3.0 start
> node index.js

Listening on 5000
Checking prices...
Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-eth-abi/src/index.js:226:15)
    at Contract._decodeMethodReturn (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-eth-contract/src/index.js:465:22)
    at Method.outputFormatter (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-eth-contract/src/index.js:818:46)
    at Method.formatOutput (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-core-method/src/index.js:473:33)
    at /Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-core-requestmanager/src/index.js:147:9
    at XMLHttpRequest.request.onreadystatechange (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/custommortgage/Documents/trading-cat/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by Chewbye** [comment]
Same issue here :(

Coming from the line:
uniswapFactoryContract.methods.getExchange(outputTokenAddress).call()

**Comment by ghost** [comment]
Same issue here :(
