### ISSUE TITLE
Error: Returned error: execution reverted

### ISSUE THREAD

**Issue by alexshelto** [dappuniversity/price-bot#26]
Getting this error on any check pair that is not ETH -> MKR. 

Things I have done: 
1. Ensured I have a correct RPC_URL
2. Commented out all other check pairs and tried them all 
3. ensured I have all npm packages

The complete error:
```
Listening on 5000
Checking prices...
Error: Returned error: execution reverted
    at Object.ErrorResponse (/Users/zoso/Dev/crypto/price-bot/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/zoso/Dev/crypto/price-bot/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/zoso/Dev/crypto/price-bot/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/zoso/Dev/crypto/price-bot/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/zoso/Dev/crypto/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/zoso/Dev/crypto/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/zoso/Dev/crypto/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by tha-gh** [comment]
I had the same problem...
I had some errors during the dependencies install process, but i could not fix it..

**Comment by theoskille** [comment]
same issue. except mine is even wierder because it prints the MKR line and then it reverts on the next checkpair call

**Comment by Esteezed** [comment]
Hi,
Go check @mohamedalichelbi PR https://github.com/dappuniversity/price-bot/pull/13

Cheers

**Comment by vikas-speqto** [comment]
Hello @MYCRYPTOTV ,

Yes PR [13](https://github.com/dappuniversity/price-bot/pull/13) works for me too, Cheers Guys.

**Comment by dixit-kava** [comment]
> same issue. except mine is even wierder because it prints the MKR line and then it reverts on the next checkpair call

did you got the answer ?? I am also facing the same issue.
