### ISSUE TITLE
Please pass numbers as strings or BN objects to avoid precision errors.

### ISSUE THREAD

**Issue by Ayestorv** [dappuniversity/price-bot#31]
I was getting a bunch of errors but i managed around them but now this is the final boss fight.

Error: Please pass numbers as strings or BN objects to avoid precision errors.
    at Object.fromWei (/mnt/d/cryptobot/price-bot/node_modules/web3-utils/lib/index.js:219:15)
    at checkPair (/mnt/d/cryptobot/price-bot/index.js:48:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async monitorPrice (/mnt/d/cryptobot/price-bot/index.js:68:5)
    at async Timeout._onTimeout (/mnt/d/cryptobot/price-bot/index.js:112:42)

I have no idea what its talking about i checked everything that i imagine could be causing it but no idea to be honest

**Comment by Ayestorv** [comment]
fixed i had to update the kyber min result to worstRate
