### ISSUE TITLE
Error: Returned error: execution reverted

### ISSUE THREAD

**Issue by MuhammadKhalil531** [dappuniversity/price-bot#43]
Listening on 5000
Checking prices...
┌─────────┬─────────────┬──────────────┬──────────────┬────────────────────────┬────────────────────────┬───────────────────────┬─────────────────────────────┐
│ (index) │ Input Token │ Output Token │ Input Amount │     Uniswap Return     │  Kyber Expected Rate   │   Kyber Min Return    │          Timestamp          │
├─────────┼─────────────┼──────────────┼──────────────┼────────────────────────┼────────────────────────┼───────────────────────┼─────────────────────────────┤
│    0    │    'ETH'    │    'MKR'     │     '1'      │ '2.260300770597604295' │ '2.260080079622844114' │ '2.19227767723415879' │ '2022-09-15T00:15:18-05:00' │
└─────────┴─────────────┴──────────────┴──────────────┴────────────────────────┴────────────────────────┴───────────────────────┴─────────────────────────────┘
Error: Returned error: execution reverted
    at Object.ErrorResponse (/Users/Desktop/dapp-bot/price-bot/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/Desktop/dapp-bot/price-bot/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/Desktop/dapp-bot/price-bot/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/Desktop/dapp-bot/price-bot/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/Users/Desktop/dapp-bot/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/Users/Desktop/dapp-bot/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/Users/Desktop/dapp-bot/price-bot/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by lggg123** [comment]
You at least get some prices. I get none.......

**Comment by rolandweb3** [comment]
Same here, have you solved it?
