### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::5000

### ISSUE THREAD

**Issue by TimelessArbitrage** [dappuniversity/price-bot#6]
Added my own RPC key URL and changed the input currency for the pairs to be USDC instead of ETH, but those are the only changes I've made so far. 
Every time I try to run the script, I get this error message:

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1317:16)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1451:7)
    at [stdin]:17:39
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:309:38)
    at internal/process/execution.js:77:19
    at [stdin]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:198:5)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[Finished in 1.312s]

**Comment by KinectTheUnknown** [comment]
You either still have the project running in the background, if not buried in the foreground, or another project is using that port. Check your task/process manager and make sure node isn't running if no other node.js projects are running.

**Comment by morningtundra** [comment]
Change the port# in the index.js (about line # 13). 3000 works for me.

If you're on Mac OS, then port 5000 is now reserved and used for Mac utils.
